//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.01 at 10:17:03 PM PST
//

package com.autodesk.bsm.pelican.soap.convergentcharging;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListOfContracts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Contract" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                             &lt;element name="RatePlan" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                             &lt;element name="ListOfProductBurnRates" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ProductBurnRate" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ProductLineCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                                                 &lt;element name="BurnRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                                                 &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                                                 &lt;element name="UsageCategory" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                                                 &lt;element name="JobType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "listOfContracts" })
@XmlRootElement(name = "GetProductBurnRatesResponse")
public class GetProductBurnRatesResponse {

    @XmlElement(name = "ListOfContracts")
    protected GetProductBurnRatesResponse.ListOfContracts listOfContracts;

    /**
     * Gets the value of the listOfContracts property.
     *
     * @return possible object is {@link GetProductBurnRatesResponse.ListOfContracts }
     */
    public GetProductBurnRatesResponse.ListOfContracts getListOfContracts() {
        return listOfContracts;
    }

    /**
     * Sets the value of the listOfContracts property.
     *
     * @param value allowed object is {@link GetProductBurnRatesResponse.ListOfContracts }
     */
    public void setListOfContracts(final GetProductBurnRatesResponse.ListOfContracts value) {
        this.listOfContracts = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * <p>
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Contract" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                   &lt;element name="RatePlan" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                   &lt;element name="ListOfProductBurnRates" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ProductBurnRate" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ProductLineCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                                       &lt;element name="BurnRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *                                       &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                                       &lt;element name="UsageCategory" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                                       &lt;element name="JobType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "contract" })
    public static class ListOfContracts {

        @XmlElement(name = "Contract")
        protected List<Contract> contract;

        /**
         * Gets the value of the contract property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the contract property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getContract().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetProductBurnRatesResponse.ListOfContracts.Contract }
         */
        public List<Contract> getContract() {
            if (contract == null) {
                contract = new ArrayList<>();
            }
            return this.contract;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * <p>
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * <p>
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *         &lt;element name="RatePlan" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *         &lt;element name="ListOfProductBurnRates" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ProductBurnRate" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ProductLineCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *                             &lt;element name="BurnRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
         *                             &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *                             &lt;element name="UsageCategory" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *                             &lt;element name="JobType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "contractNumber", "ratePlan", "listOfProductBurnRates" })
        public static class Contract {

            @XmlElement(name = "ContractNumber")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String contractNumber;
            @XmlElement(name = "RatePlan")
            @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
            @XmlSchemaType(name = "normalizedString")
            protected String ratePlan;
            @XmlElement(name = "ListOfProductBurnRates")
            protected GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates listOfProductBurnRates;

            /**
             * Gets the value of the contractNumber property.
             *
             * @return possible object is {@link String }
             */
            public String getContractNumber() {
                return contractNumber;
            }

            /**
             * Sets the value of the contractNumber property.
             *
             * @param value allowed object is {@link String }
             */
            public void setContractNumber(final String value) {
                this.contractNumber = value;
            }

            /**
             * Gets the value of the ratePlan property.
             *
             * @return possible object is {@link String }
             */
            public String getRatePlan() {
                return ratePlan;
            }

            /**
             * Sets the value of the ratePlan property.
             *
             * @param value allowed object is {@link String }
             */
            public void setRatePlan(final String value) {
                this.ratePlan = value;
            }

            /**
             * Gets the value of the listOfProductBurnRates property.
             *
             * @return possible object is
             *         {@link GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates }
             */
            public GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates getListOfProductBurnRates() {
                return listOfProductBurnRates;
            }

            /**
             * Sets the value of the listOfProductBurnRates property.
             *
             * @param value allowed object is
             *        {@link GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates }
             */
            public void setListOfProductBurnRates(
                final GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates value) {
                this.listOfProductBurnRates = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             * <p>
             * <p>
             * The following schema fragment specifies the expected content contained within this class.
             * <p>
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ProductBurnRate" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ProductLineCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
             *                   &lt;element name="BurnRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
             *                   &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
             *                   &lt;element name="UsageCategory" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
             *                   &lt;element name="JobType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = { "productBurnRate" })
            public static class ListOfProductBurnRates {

                @XmlElement(name = "ProductBurnRate")
                protected List<ProductBurnRate> productBurnRate;

                /**
                 * Gets the value of the productBurnRate property.
                 * <p>
                 * <p>
                 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification
                 * you make to the returned list will be present inside the JAXB object. This is why there is not a
                 * <CODE>set</CODE> method for the productBurnRate property.
                 * <p>
                 * <p>
                 * For example, to add a new item, do as follows:
                 *
                 * <pre>
                 * getProductBurnRate().add(newItem);
                 * </pre>
                 * <p>
                 * <p>
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates.ProductBurnRate }
                 */
                public List<ProductBurnRate> getProductBurnRate() {
                    if (productBurnRate == null) {
                        productBurnRate = new ArrayList<>();
                    }
                    return this.productBurnRate;
                }

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 * <p>
                 * <p>
                 * The following schema fragment specifies the expected content contained within this class.
                 * <p>
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ProductLineCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
                 *         &lt;element name="BurnRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
                 *         &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
                 *         &lt;element name="UsageCategory" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
                 *         &lt;element name="JobType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "",
                    propOrder = { "productLineCode", "burnRate", "unitOfMeasure", "usageCategory", "jobType" })
                public static class ProductBurnRate {

                    @XmlElement(name = "ProductLineCode")
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String productLineCode;
                    @XmlElement(name = "BurnRate")
                    protected Double burnRate;
                    @XmlElement(name = "UnitOfMeasure")
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String unitOfMeasure;
                    @XmlElement(name = "UsageCategory")
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String usageCategory;
                    @XmlElement(name = "JobType")
                    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
                    @XmlSchemaType(name = "normalizedString")
                    protected String jobType;

                    /**
                     * Gets the value of the productLineCode property.
                     *
                     * @return possible object is {@link String }
                     */
                    public String getProductLineCode() {
                        return productLineCode;
                    }

                    /**
                     * Sets the value of the productLineCode property.
                     *
                     * @param value allowed object is {@link String }
                     */
                    public void setProductLineCode(final String value) {
                        this.productLineCode = value;
                    }

                    /**
                     * Gets the value of the burnRate property.
                     *
                     * @return possible object is {@link Double }
                     */
                    public Double getBurnRate() {
                        return burnRate;
                    }

                    /**
                     * Sets the value of the burnRate property.
                     *
                     * @param value allowed object is {@link Double }
                     */
                    public void setBurnRate(final Double value) {
                        this.burnRate = value;
                    }

                    /**
                     * Gets the value of the unitOfMeasure property.
                     *
                     * @return possible object is {@link String }
                     */
                    public String getUnitOfMeasure() {
                        return unitOfMeasure;
                    }

                    /**
                     * Sets the value of the unitOfMeasure property.
                     *
                     * @param value allowed object is {@link String }
                     */
                    public void setUnitOfMeasure(final String value) {
                        this.unitOfMeasure = value;
                    }

                    /**
                     * Gets the value of the usageCategory property.
                     *
                     * @return possible object is {@link String }
                     */
                    public String getUsageCategory() {
                        return usageCategory;
                    }

                    /**
                     * Sets the value of the usageCategory property.
                     *
                     * @param value allowed object is {@link String }
                     */
                    public void setUsageCategory(final String value) {
                        this.usageCategory = value;
                    }

                    /**
                     * Gets the value of the jobType property.
                     *
                     * @return possible object is {@link String }
                     */
                    public String getJobType() {
                        return jobType;
                    }

                    /**
                     * Sets the value of the jobType property.
                     *
                     * @param value allowed object is {@link String }
                     */
                    public void setJobType(final String value) {
                        this.jobType = value;
                    }

                }

            }

        }

    }

}
