//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.01 at 10:17:03 PM PST
//

package com.autodesk.bsm.pelican.soap.convergentcharging;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * com.autodesk.bsm.pelican.schemas.convergentchargingv1 package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _UpdateAccountResponse_QNAME =
        new QName("http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0", "UpdateAccountResponse");
    private static final QName _UpdateAccountRequest_QNAME =
        new QName("http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0", "UpdateAccountRequest");
    private static final QName _ProcessSubscriptionResponse_QNAME =
        new QName("http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0", "ProcessSubscriptionResponse");
    private static final QName _ProvisionCreditsResponse_QNAME =
        new QName("http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0", "ProvisionCreditsResponse");
    private static final QName _AccountBaseDataTypeAccountName_QNAME = new QName("", "AccountName");
    private static final QName _OxygenIdGuidBaseDataTypeOxygenId_QNAME = new QName("", "OxygenId");
    private static final QName _OxygenIdGuidBaseDataTypeGuid_QNAME = new QName("", "Guid");
    private static final QName _AccountRefDataTypeId_QNAME = new QName("", "Id");
    private static final QName _AccountRefDataTypeUUID_QNAME = new QName("", "UUID");
    private static final QName _AccountRefDataTypeAccountCSN_QNAME = new QName("", "AccountCSN");
    private static final QName _ContractRefDataTypeContractNumber_QNAME = new QName("", "ContractNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * com.autodesk.bsm.pelican.schemas.convergentchargingv1
     */
    public ObjectFactory() {}

    /**
     * Create an instance of {@link GetCcTransactionsRequest }
     */
    public GetCcTransactionsRequest createGetCcTransactionsRequest() {
        return new GetCcTransactionsRequest();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesResponse }
     */
    public GetProductBurnRatesResponse createGetProductBurnRatesResponse() {
        return new GetProductBurnRatesResponse();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryResponse }
     */
    public GetCcTransactionSummaryResponse createGetCcTransactionSummaryResponse() {
        return new GetCcTransactionSummaryResponse();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryRequest }
     */
    public GetCcTransactionSummaryRequest createGetCcTransactionSummaryRequest() {
        return new GetCcTransactionSummaryRequest();
    }

    /**
     * Create an instance of {@link GetCcUsageSummaryResponse }
     */
    public GetCcUsageSummaryResponse createGetCcUsageSummaryResponse() {
        return new GetCcUsageSummaryResponse();
    }

    /**
     * Create an instance of {@link GetCcUsageSummaryRequest }
     */
    public GetCcUsageSummaryRequest createGetCcUsageSummaryRequest() {
        return new GetCcUsageSummaryRequest();
    }

    /**
     * Create an instance of {@link ProcessSubscriptionRequest }
     */
    public ProcessSubscriptionRequest createProcessSubscriptionRequest() {
        return new ProcessSubscriptionRequest();
    }

    /**
     * Create an instance of {@link ProvisionCreditsRequest }
     */
    public ProvisionCreditsRequest createProvisionCreditsRequest() {
        return new ProvisionCreditsRequest();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceRequest }
     */
    public QuerySubscriptionBalanceRequest createQuerySubscriptionBalanceRequest() {
        return new QuerySubscriptionBalanceRequest();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesRequest }
     */
    public GetProductBurnRatesRequest createGetProductBurnRatesRequest() {
        return new GetProductBurnRatesRequest();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceResponse }
     */
    public QuerySubscriptionBalanceResponse createQuerySubscriptionBalanceResponse() {
        return new QuerySubscriptionBalanceResponse();
    }

    /**
     * Create an instance of {@link GetCcTransactionsResponse }
     */
    public GetCcTransactionsResponse createGetCcTransactionsResponse() {
        return new GetCcTransactionsResponse();
    }

    /**
     * Create an instance of {@link ServicePrivilege }
     */
    public ServicePrivilege createServicePrivilege() {
        return new ServicePrivilege();
    }

    /**
     * Create an instance of {@link GetCcTransactionsResponse.ListOfCcTransactions }
     */
    public GetCcTransactionsResponse.ListOfCcTransactions createGetCcTransactionsResponseListOfCcTransactions() {
        return new GetCcTransactionsResponse.ListOfCcTransactions();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceResponse.ListOfContracts }
     */
    public QuerySubscriptionBalanceResponse.ListOfContracts createQuerySubscriptionBalanceResponseListOfContracts() {
        return new QuerySubscriptionBalanceResponse.ListOfContracts();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceResponse.ListOfContracts.Contract }
     */
    public QuerySubscriptionBalanceResponse.ListOfContracts.Contract createQuerySubscriptionBalanceResponseListOfContractsContract() {
        return new QuerySubscriptionBalanceResponse.ListOfContracts.Contract();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesRequest.ListOfContracts }
     */
    public GetProductBurnRatesRequest.ListOfContracts createGetProductBurnRatesRequestListOfContracts() {
        return new GetProductBurnRatesRequest.ListOfContracts();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceRequest.ListOfContracts }
     */
    public QuerySubscriptionBalanceRequest.ListOfContracts createQuerySubscriptionBalanceRequestListOfContracts() {
        return new QuerySubscriptionBalanceRequest.ListOfContracts();
    }

    /**
     * Create an instance of {@link GetCcUsageSummaryResponse.ListOfCcUsageSummary }
     */
    public GetCcUsageSummaryResponse.ListOfCcUsageSummary createGetCcUsageSummaryResponseListOfCcUsageSummary() {
        return new GetCcUsageSummaryResponse.ListOfCcUsageSummary();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryResponse.ListOfCcTransactionSummary }
     */
    public GetCcTransactionSummaryResponse.ListOfCcTransactionSummary createGetCcTransactionSummaryResponseListOfCcTransactionSummary() {
        return new GetCcTransactionSummaryResponse.ListOfCcTransactionSummary();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesResponse.ListOfContracts }
     */
    public GetProductBurnRatesResponse.ListOfContracts createGetProductBurnRatesResponseListOfContracts() {
        return new GetProductBurnRatesResponse.ListOfContracts();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesResponse.ListOfContracts.Contract }
     */
    public GetProductBurnRatesResponse.ListOfContracts.Contract createGetProductBurnRatesResponseListOfContractsContract() {
        return new GetProductBurnRatesResponse.ListOfContracts.Contract();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates }
     */
    public GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates createGetProductBurnRatesResponseListOfContractsContractListOfProductBurnRates() {
        return new GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates();
    }

    /**
     * Create an instance of {@link AccountBaseDataType }
     */
    public AccountBaseDataType createAccountBaseDataType() {
        return new AccountBaseDataType();
    }

    /**
     * Create an instance of {@link ResponseType }
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link GetCcTransactionsRequest.ListOfContractNumbers }
     */
    public GetCcTransactionsRequest.ListOfContractNumbers createGetCcTransactionsRequestListOfContractNumbers() {
        return new GetCcTransactionsRequest.ListOfContractNumbers();
    }

    /**
     * Create an instance of {@link GetCcTransactionsRequest.ListOfAccountCSN }
     */
    public GetCcTransactionsRequest.ListOfAccountCSN createGetCcTransactionsRequestListOfAccountCSN() {
        return new GetCcTransactionsRequest.ListOfAccountCSN();
    }

    /**
     * Create an instance of {@link GetCcTransactionsRequest.ListOfGuids }
     */
    public GetCcTransactionsRequest.ListOfGuids createGetCcTransactionsRequestListOfGuids() {
        return new GetCcTransactionsRequest.ListOfGuids();
    }

    /**
     * Create an instance of {@link GetCcTransactionsRequest.ListOfJobUids }
     */
    public GetCcTransactionsRequest.ListOfJobUids createGetCcTransactionsRequestListOfJobUids() {
        return new GetCcTransactionsRequest.ListOfJobUids();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryRequest.ListOfContractNumbers }
     */
    public GetCcTransactionSummaryRequest.ListOfContractNumbers createGetCcTransactionSummaryRequestListOfContractNumbers() {
        return new GetCcTransactionSummaryRequest.ListOfContractNumbers();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryRequest.ListOfAccountCSN }
     */
    public GetCcTransactionSummaryRequest.ListOfAccountCSN createGetCcTransactionSummaryRequestListOfAccountCSN() {
        return new GetCcTransactionSummaryRequest.ListOfAccountCSN();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryRequest.ListOfGuids }
     */
    public GetCcTransactionSummaryRequest.ListOfGuids createGetCcTransactionSummaryRequestListOfGuids() {
        return new GetCcTransactionSummaryRequest.ListOfGuids();
    }

    /**
     * Create an instance of {@link GetCcUsageSummaryRequest.ListOfContracts }
     */
    public GetCcUsageSummaryRequest.ListOfContracts createGetCcUsageSummaryRequestListOfContracts() {
        return new GetCcUsageSummaryRequest.ListOfContracts();
    }

    /**
     * Create an instance of {@link GetCcUsageSummaryRequest.ListOfGuids }
     */
    public GetCcUsageSummaryRequest.ListOfGuids createGetCcUsageSummaryRequestListOfGuids() {
        return new GetCcUsageSummaryRequest.ListOfGuids();
    }

    /**
     * Create an instance of {@link ContractBaseDataType }
     */
    public ContractBaseDataType createContractBaseDataType() {
        return new ContractBaseDataType();
    }

    /**
     * Create an instance of {@link ProcessSubscriptionRequest.ListOfProducts }
     */
    public ProcessSubscriptionRequest.ListOfProducts createProcessSubscriptionRequestListOfProducts() {
        return new ProcessSubscriptionRequest.ListOfProducts();
    }

    /**
     * Create an instance of {@link SOAPFault }
     */
    public SOAPFault createSOAPFault() {
        return new SOAPFault();
    }

    /**
     * Create an instance of {@link SOAPFaultType }
     */
    public SOAPFaultType createSOAPFaultType() {
        return new SOAPFaultType();
    }

    /**
     * Create an instance of {@link OxygenIdGuidBaseDataType }
     */
    public OxygenIdGuidBaseDataType createOxygenIdGuidBaseDataType() {
        return new OxygenIdGuidBaseDataType();
    }

    /**
     * Create an instance of {@link ProvisionCreditsRequest.ListOfProducts }
     */
    public ProvisionCreditsRequest.ListOfProducts createProvisionCreditsRequestListOfProducts() {
        return new ProvisionCreditsRequest.ListOfProducts();
    }

    /**
     * Create an instance of {@link ContractRefDataType }
     */
    public ContractRefDataType createContractRefDataType() {
        return new ContractRefDataType();
    }

    /**
     * Create an instance of {@link ProductAttributeType }
     */
    public ProductAttributeType createProductAttributeType() {
        return new ProductAttributeType();
    }

    /**
     * Create an instance of {@link AccountRefDataType }
     */
    public AccountRefDataType createAccountRefDataType() {
        return new AccountRefDataType();
    }

    /**
     * Create an instance of {@link ProductType }
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link Unit }
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link ServicePrivilege.ListOfUnits }
     */
    public ServicePrivilege.ListOfUnits createServicePrivilegeListOfUnits() {
        return new ServicePrivilege.ListOfUnits();
    }

    /**
     * Create an instance of {@link GetCcTransactionsResponse.ListOfCcTransactions.CcTransaction }
     */
    public GetCcTransactionsResponse.ListOfCcTransactions.CcTransaction createGetCcTransactionsResponseListOfCcTransactionsCcTransaction() {
        return new GetCcTransactionsResponse.ListOfCcTransactions.CcTransaction();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceResponse.ListOfContracts.Contract.ListOfServicePrivileges }
     */
    public QuerySubscriptionBalanceResponse.ListOfContracts.Contract.ListOfServicePrivileges createQuerySubscriptionBalanceResponseListOfContractsContractListOfServicePrivileges() {
        return new QuerySubscriptionBalanceResponse.ListOfContracts.Contract.ListOfServicePrivileges();
    }

    /**
     * Create an instance of {@link GetProductBurnRatesRequest.ListOfContracts.Contract }
     */
    public GetProductBurnRatesRequest.ListOfContracts.Contract createGetProductBurnRatesRequestListOfContractsContract() {
        return new GetProductBurnRatesRequest.ListOfContracts.Contract();
    }

    /**
     * Create an instance of {@link QuerySubscriptionBalanceRequest.ListOfContracts.Contract }
     */
    public QuerySubscriptionBalanceRequest.ListOfContracts.Contract createQuerySubscriptionBalanceRequestListOfContractsContract() {
        return new QuerySubscriptionBalanceRequest.ListOfContracts.Contract();
    }

    /**
     * Create an instance of {@link GetCcUsageSummaryResponse.ListOfCcUsageSummary.CcSummaryUsage }
     */
    public GetCcUsageSummaryResponse.ListOfCcUsageSummary.CcSummaryUsage createGetCcUsageSummaryResponseListOfCcUsageSummaryCcSummaryUsage() {
        return new GetCcUsageSummaryResponse.ListOfCcUsageSummary.CcSummaryUsage();
    }

    /**
     * Create an instance of {@link GetCcTransactionSummaryResponse.ListOfCcTransactionSummary.CcSummaryTransaction }
     */
    public GetCcTransactionSummaryResponse.ListOfCcTransactionSummary.CcSummaryTransaction createGetCcTransactionSummaryResponseListOfCcTransactionSummaryCcSummaryTransaction() {
        return new GetCcTransactionSummaryResponse.ListOfCcTransactionSummary.CcSummaryTransaction();
    }

    /**
     * Create an instance of
     * {@link GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates.ProductBurnRate }
     */
    public GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates.ProductBurnRate createGetProductBurnRatesResponseListOfContractsContractListOfProductBurnRatesProductBurnRate() {
        return new GetProductBurnRatesResponse.ListOfContracts.Contract.ListOfProductBurnRates.ProductBurnRate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0",
        name = "UpdateAccountResponse")
    public JAXBElement<ResponseType> createUpdateAccountResponse(final ResponseType value) {
        return new JAXBElement<>(_UpdateAccountResponse_QNAME, ResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountBaseDataType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0",
        name = "UpdateAccountRequest")
    public JAXBElement<AccountBaseDataType> createUpdateAccountRequest(final AccountBaseDataType value) {
        return new JAXBElement<>(_UpdateAccountRequest_QNAME, AccountBaseDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0",
        name = "ProcessSubscriptionResponse")
    public JAXBElement<ResponseType> createProcessSubscriptionResponse(final ResponseType value) {
        return new JAXBElement<>(_ProcessSubscriptionResponse_QNAME, ResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     */
    @XmlElementDecl(namespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0",
        name = "ProvisionCreditsResponse")
    public JAXBElement<ResponseType> createProvisionCreditsResponse(final ResponseType value) {
        return new JAXBElement<>(_ProvisionCreditsResponse_QNAME, ResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "AccountName", scope = AccountBaseDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAccountBaseDataTypeAccountName(final String value) {
        return new JAXBElement<>(_AccountBaseDataTypeAccountName_QNAME, String.class, AccountBaseDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "OxygenId", scope = OxygenIdGuidBaseDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOxygenIdGuidBaseDataTypeOxygenId(final String value) {
        return new JAXBElement<>(_OxygenIdGuidBaseDataTypeOxygenId_QNAME, String.class, OxygenIdGuidBaseDataType.class,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Guid", scope = OxygenIdGuidBaseDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createOxygenIdGuidBaseDataTypeGuid(final String value) {
        return new JAXBElement<>(_OxygenIdGuidBaseDataTypeGuid_QNAME, String.class, OxygenIdGuidBaseDataType.class,
            value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Id", scope = AccountRefDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAccountRefDataTypeId(final String value) {
        return new JAXBElement<>(_AccountRefDataTypeId_QNAME, String.class, AccountRefDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "UUID", scope = AccountRefDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAccountRefDataTypeUUID(final String value) {
        return new JAXBElement<>(_AccountRefDataTypeUUID_QNAME, String.class, AccountRefDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "AccountCSN", scope = AccountRefDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createAccountRefDataTypeAccountCSN(final String value) {
        return new JAXBElement<>(_AccountRefDataTypeAccountCSN_QNAME, String.class, AccountRefDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ContractNumber", scope = ContractRefDataType.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createContractRefDataTypeContractNumber(final String value) {
        return new JAXBElement<>(_ContractRefDataTypeContractNumber_QNAME, String.class, ContractRefDataType.class,
            value);
    }

}
