//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.01 at 10:17:03 PM PST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0")
package com.autodesk.bsm.pelican.soap.convergentcharging;
