//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.01 at 10:17:03 PM PST
//

package com.autodesk.bsm.pelican.soap.convergentcharging;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ProductType complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductContractStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ProductContractEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ProductLine" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ProductLineCode" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ProductUsage" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="Quantity" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="SubscriptionLevel" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="ServiceSaleType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="Year1Tokens" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Year2Tokens" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Year3Tokens" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Year4Tokens" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Year5Tokens" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="MultiYearTokens" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="StorageUnit" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType",
    propOrder = { "productContractStartDate", "productContractEndDate", "productLine", "productLineCode",
            "productUsage", "quantity", "subscriptionLevel", "serviceSaleType", "year1Tokens", "year2Tokens",
            "year3Tokens", "year4Tokens", "year5Tokens", "multiYearTokens", "storageUnit" })
public class ProductType {

    @XmlElement(name = "ProductContractStartDate")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar productContractStartDate;
    @XmlElement(name = "ProductContractEndDate")
    @XmlSchemaType(name = "date")
    private XMLGregorianCalendar productContractEndDate;
    @XmlElement(name = "ProductLine")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    private String productLine;
    @XmlElement(name = "ProductLineCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    private String productLineCode;
    @XmlElement(name = "ProductUsage")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    private String productUsage;
    @XmlElement(name = "Quantity")
    private BigInteger quantity;
    @XmlElement(name = "SubscriptionLevel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    private String subscriptionLevel;
    @XmlElement(name = "ServiceSaleType")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    private String serviceSaleType;
    @XmlElement(name = "Year1Tokens")
    private BigInteger year1Tokens;
    @XmlElement(name = "Year2Tokens")
    private BigInteger year2Tokens;
    @XmlElement(name = "Year3Tokens")
    private BigInteger year3Tokens;
    @XmlElement(name = "Year4Tokens")
    private BigInteger year4Tokens;
    @XmlElement(name = "Year5Tokens")
    private BigInteger year5Tokens;
    @XmlElement(name = "MultiYearTokens")
    private BigInteger multiYearTokens;
    @XmlElement(name = "StorageUnit")
    private BigInteger storageUnit;

    /**
     * Gets the value of the productContractStartDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getProductContractStartDate() {
        return productContractStartDate;
    }

    /**
     * Sets the value of the productContractStartDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     */
    public void setProductContractStartDate(final XMLGregorianCalendar value) {
        this.productContractStartDate = value;
    }

    /**
     * Gets the value of the productContractEndDate property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getProductContractEndDate() {
        return productContractEndDate;
    }

    /**
     * Sets the value of the productContractEndDate property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     */
    public void setProductContractEndDate(final XMLGregorianCalendar value) {
        this.productContractEndDate = value;
    }

    /**
     * Gets the value of the productLine property.
     *
     * @return possible object is {@link String }
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * Sets the value of the productLine property.
     *
     * @param value allowed object is {@link String }
     */
    public void setProductLine(final String value) {
        this.productLine = value;
    }

    /**
     * Gets the value of the productLineCode property.
     *
     * @return possible object is {@link String }
     */
    public String getProductLineCode() {
        return productLineCode;
    }

    /**
     * Sets the value of the productLineCode property.
     *
     * @param value allowed object is {@link String }
     */
    public void setProductLineCode(final String value) {
        this.productLineCode = value;
    }

    /**
     * Gets the value of the productUsage property.
     *
     * @return possible object is {@link String }
     */
    public String getProductUsage() {
        return productUsage;
    }

    /**
     * Sets the value of the productUsage property.
     *
     * @param value allowed object is {@link String }
     */
    public void setProductUsage(final String value) {
        this.productUsage = value;
    }

    /**
     * Gets the value of the quantity property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setQuantity(final BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the subscriptionLevel property.
     *
     * @return possible object is {@link String }
     */
    public String getSubscriptionLevel() {
        return subscriptionLevel;
    }

    /**
     * Sets the value of the subscriptionLevel property.
     *
     * @param value allowed object is {@link String }
     */
    public void setSubscriptionLevel(final String value) {
        this.subscriptionLevel = value;
    }

    /**
     * Gets the value of the serviceSaleType property.
     *
     * @return possible object is {@link String }
     */
    public String getServiceSaleType() {
        return serviceSaleType;
    }

    /**
     * Sets the value of the serviceSaleType property.
     *
     * @param value allowed object is {@link String }
     */
    public void setServiceSaleType(final String value) {
        this.serviceSaleType = value;
    }

    /**
     * Gets the value of the year1Tokens property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getYear1Tokens() {
        return year1Tokens;
    }

    /**
     * Sets the value of the year1Tokens property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setYear1Tokens(final BigInteger value) {
        this.year1Tokens = value;
    }

    /**
     * Gets the value of the year2Tokens property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getYear2Tokens() {
        return year2Tokens;
    }

    /**
     * Sets the value of the year2Tokens property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setYear2Tokens(final BigInteger value) {
        this.year2Tokens = value;
    }

    /**
     * Gets the value of the year3Tokens property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getYear3Tokens() {
        return year3Tokens;
    }

    /**
     * Sets the value of the year3Tokens property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setYear3Tokens(final BigInteger value) {
        this.year3Tokens = value;
    }

    /**
     * Gets the value of the year4Tokens property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getYear4Tokens() {
        return year4Tokens;
    }

    /**
     * Sets the value of the year4Tokens property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setYear4Tokens(final BigInteger value) {
        this.year4Tokens = value;
    }

    /**
     * Gets the value of the year5Tokens property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getYear5Tokens() {
        return year5Tokens;
    }

    /**
     * Sets the value of the year5Tokens property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setYear5Tokens(final BigInteger value) {
        this.year5Tokens = value;
    }

    /**
     * Gets the value of the multiYearTokens property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getMultiYearTokens() {
        return multiYearTokens;
    }

    /**
     * Sets the value of the multiYearTokens property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setMultiYearTokens(final BigInteger value) {
        this.multiYearTokens = value;
    }

    /**
     * Gets the value of the storageUnit property.
     *
     * @return possible object is {@link BigInteger }
     */
    public BigInteger getStorageUnit() {
        return storageUnit;
    }

    /**
     * Sets the value of the storageUnit property.
     *
     * @param value allowed object is {@link BigInteger }
     */
    public void setStorageUnit(final BigInteger value) {
        this.storageUnit = value;
    }

}
