//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.02.01 at 10:17:03 PM PST
//

package com.autodesk.bsm.pelican.soap.convergentcharging;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contract" type="{http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0}OxygenIdGuidBaseDataType" minOccurs="0"/>
 *         &lt;element name="EndUserAccount" type="{http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0}AccountBaseDataType" minOccurs="0"/>
 *         &lt;element name="ListOfProducts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Product" type="{http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0}ProductType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "contract", "endUserAccount", "listOfProducts" })
@XmlRootElement(name = "ProvisionCreditsRequest")
public class ProvisionCreditsRequest {

    @XmlElement(name = "Contract")
    protected OxygenIdGuidBaseDataType contract;
    @XmlElement(name = "EndUserAccount")
    protected AccountBaseDataType endUserAccount;
    @XmlElement(name = "ListOfProducts")
    protected ProvisionCreditsRequest.ListOfProducts listOfProducts;

    /**
     * Gets the value of the contract property.
     *
     * @return possible object is {@link OxygenIdGuidBaseDataType }
     */
    public OxygenIdGuidBaseDataType getContract() {
        return contract;
    }

    /**
     * Sets the value of the contract property.
     *
     * @param value allowed object is {@link OxygenIdGuidBaseDataType }
     */
    public void setContract(final OxygenIdGuidBaseDataType value) {
        this.contract = value;
    }

    /**
     * Gets the value of the endUserAccount property.
     *
     * @return possible object is {@link AccountBaseDataType }
     */
    public AccountBaseDataType getEndUserAccount() {
        return endUserAccount;
    }

    /**
     * Sets the value of the endUserAccount property.
     *
     * @param value allowed object is {@link AccountBaseDataType }
     */
    public void setEndUserAccount(final AccountBaseDataType value) {
        this.endUserAccount = value;
    }

    /**
     * Gets the value of the listOfProducts property.
     *
     * @return possible object is {@link ProvisionCreditsRequest.ListOfProducts }
     */
    public ProvisionCreditsRequest.ListOfProducts getListOfProducts() {
        return listOfProducts;
    }

    /**
     * Sets the value of the listOfProducts property.
     *
     * @param value allowed object is {@link ProvisionCreditsRequest.ListOfProducts }
     */
    public void setListOfProducts(final ProvisionCreditsRequest.ListOfProducts value) {
        this.listOfProducts = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * <p>
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * <p>
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Product" type="{http://www.autodesk.com/schemas/Business/ConvergentChargingV1.0}ProductType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "product" })
    public static class ListOfProducts {

        @XmlElement(name = "Product")
        protected List<ProductType> product;

        /**
         * Gets the value of the product property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you
         * make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE>
         * method for the product property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         *
         * <pre>
         * getProduct().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list {@link ProductType }
         */
        public List<ProductType> getProduct() {
            if (product == null) {
                product = new ArrayList<>();
            }
            return this.product;
        }

    }

}
